<a href="https://colab.research.google.com/github/liang-kan/python/blob/main/2_1_2_%E8%BF%90%E7%AE%97%E7%AC%A6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

我们的兴趣不仅限于读取数据和写入数据。我们想在这些数据上执行数学运算，其中最简单且最有用的操作时按元素（elementwise）运算。他们将标准表量运算符应用于数组的每个元素。对于将两个数组作为输入的函数，按元素运算将二元运算符应用于两个数组中的每个对应位置的元素。我们可以基于任何从标量到标量的函数。
注：https://zh.d2l.ai/chapter_preliminaries/ndarray.html  符号打不出来，详情参照d2l

对于任意具有形状的张量，常见的标准算数运算符（+、-、*、/和**）都可以被升级为按元素运算。我们可以在同一形状的仁义两个张量上调用按元素操作。在下面的例子中，我们使用逗号来表示一个具有5个元素的元组，其中每个元素都是按照元素操作的结果。


In [2]:
import torch

In [8]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y #**运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

“按元素”方式可以应用更多的计算，包括像求幂这样的一元运算符。

In [9]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])