<a href="https://colab.research.google.com/github/liang-kan/python/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


# pytorch

In [ ]:
import torch
torch.tensor([1,2,3,4],dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [ ]:
import numpy as np

In [ ]:
torch.tensor(np.array([1,2,3,4]),dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [ ]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [11]:
torch.linspace(0,100,2)

tensor([  0., 100.])

In [13]:
np.random.normal(loc=10,scale=3,size=(5,6))

array([[11.13085752, 14.31609365,  6.57180201, 12.3220394 ,  9.83761414,
         6.80471357],
       [10.96165637, 13.12608191, 10.74764508, 10.75809514,  7.02531396,
         7.13436605],
       [ 9.27100086,  9.38014259, 11.51096054, 12.94932085,  8.99220389,
        14.44776412],
       [ 9.48080949, 13.30827415,  8.56661074,  6.44771833,  7.30786183,
        11.19253269],
       [13.14936286,  9.82987275,  9.95691107,  7.78523829, 13.07327279,
        12.32408881]])

# 上面的语句可以用来确认是否开启GPU加速


In [ ]:
!gdown 'https://drive.google.com/uc?id=1H73TfV5gQ9ot7slSed_l-lim9X7pMRiU' --output Minori.jpg

Downloading...
From: https://drive.google.com/uc?id=1H73TfV5gQ9ot7slSed_l-lim9X7pMRiU
To: /content/drive/MyDrive/ML2023/Minori.jpg
100% 382M/382M [00:03<00:00, 110MB/s]


In [ ]:
!ls

Minori.jpg


In [ ]:
%cd /content/drive/MyDrive
!mkdir ML2023
%cd ./ML2023

/content/drive/MyDrive
/content/drive/MyDrive/ML2023


In [ ]:
!pwd

/content/drive/MyDrive/ML2023
