<a href="https://colab.research.google.com/github/liang-kan/python/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


# pytorch

In [ ]:
import torch
torch.tensor([1,2,3,4],dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [ ]:
import numpy as np

In [ ]:
torch.tensor(np.array([1,2,3,4]),dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [ ]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# 上面的语句可以用来确认是否开启GPU加速


In [ ]:
!gdown 'https://drive.google.com/uc?id=1H73TfV5gQ9ot7slSed_l-lim9X7pMRiU' --output Minori.jpg

Downloading...
From: https://drive.google.com/uc?id=1H73TfV5gQ9ot7slSed_l-lim9X7pMRiU
To: /content/drive/MyDrive/ML2023/Minori.jpg
100% 382M/382M [00:03<00:00, 110MB/s]


In [ ]:
!ls

Minori.jpg


In [ ]:
%cd /content/drive/MyDrive
!mkdir ML2023
%cd ./ML2023

/content/drive/MyDrive
/content/drive/MyDrive/ML2023


In [ ]:
!pwd

/content/drive/MyDrive/ML2023
